### ISSUE TITLE
[Feature] add subtitle support

### ISSUE THREAD

**Issue by medarob** [Hauer-Heinrich/hh_video_extender#8]
Hi,

it seems that webm does not support embeded subtitles into a webm file. Therefor you have to use external subtitles which can be added to a `<video>`-tag with a `<track>`-tag.

Is it possible to add subtitle support for videos?
Info: https://developer.mozilla.org/en-US/docs/Web/Guide/Audio_and_video_delivery/Adding_captions_and_subtitles_to_HTML5_video

For example, save the subtitle in the same folder (or a subfolder which has to be configured) and load it into the code. The same function you use to add other video formats like webm, ogg.

Only questions remain:

**How do you add multiple subtitles for different languages?**

This would be a solution:
clip-name.en.vtt
clip-name.de.vtt
clip-name.fr.vtt

**How to define the default subtitle?**
There exists a `default` attribut which indicats to the browser that this is the default subtitle file definition. How to define that so that it works for multilanguage?

I thought about adding the default option to the filename to indicate that this is the default subtitle, like this `clip-name.de.default.vtt`. Problem: Does this work when the CE was translated into another language? On a French website the default subtitle schould be in French as well. (Of course the user can change the subtitle in the frontend, so maybe that would be a minor issue.)

A better way would be to list all available subtitles for a videofile in the backend and the editor can choose the default subtitle. But not sure if that is possible?

**Comment by medarob** [comment]
Ok, I tested it.

I created a Text&Media element and added a video file located in `fileadmin/somefolder/to/videofile/testvideo.mp4`

I created a folder `fileadmin/somefolder/to/videofile/testvideo/de/captions.vtt` and added the following:
```
WEBVTT Einführung

NOTE This is a multi-line note block.
These are used for comments by the author
Two cue blocks are defined below.

00:00:05.000 --> 00:00:10.000
Teil 1 – Grundlagen

00:00:10.000 --> 00:00:17.000
Teil 2 – Fortgeschrittene Techniken
```
But the caption does not appear in the source code in a `<source>` tag and therefor does not appear in the video.

**Comment by Teisi** [comment]
Oh yes, that's a mistake.
What would you prefer, if the folder has to be named the same as the video, or with the addition “_tracks”?
I thought I would add “_tracks” for the sake of clarity and structuring the fileadmin - but what do you think?

Improved (new master) - tack-label customization (see readme):

##### If you want custom track-labels
Default (fallback): uses the "title" of the language from your site config.yaml
Custom:
Add an entry below "videoTracks" -> "labels" for each language in your site config.yaml for each type of track (structure is important), e. g.:
```
languages:
  -
    title: English
    enabled: true
    languageId: '1'
    base: /en/
    typo3Language: en
    locale: en_US.UTF-8
    iso-639-1: en
    navigationTitle: EN
    hreflang: en
    direction: ltr
    fallbackType: free
    fallbacks: '0'
    flag: en-us-gb
    videoTracks:
      labels:
        captions: custom label for caption
        subtitles: label customized for subtiles
```

Thank you for testing and the gut hint : custom track labels :)
